version: '2.0'

services:
  sjbha-app:
    build: .
    command: npm start
    environment:
      NODE_ENV: "production"
      DEBUG: "@services*,@app:*,@plugins:*"
    env_file: ./.env

    ports:
      - "5000:5000"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy