version: '2.0'

services:
  sjbha-app:
    build: .
    environment:
      NODE_ENV: "production"
      DEBUG: "@sjbha*"
      HOSTNAME: "https://sjbha.s3bby.com"

      VIRTUAL_HOST: "sjbha.s3bby.com"
      VIRTUAL_PORT: 5000

      LETSENCRYPT_HOST: "sjbha.s3bby.com"
      LETSENCRYPT_EMAIL: "sebhendowski@gmail.com"
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy